version: '3.8'

services:
  app:
    build:
      context: .  # Use the Dockerfile in the current directory
    ports:
      - "3000:3000"  # Map the container port 3000 to host port 3000
    environment:
      - DB_NAME=${DB_NAME}  
      - DB_USER=${DB_USER}  
      - DB_PASSWORD=${DB_PASSWORD}  
      - DB_HOST=${DB_HOST}  
      - DB_PORT=${DB_PORT}  
      - DB_DIALECT=${DB_DIALECT}  
      - NODE_ENV=${NODE_ENV}  
    depends_on:
      - db  # Wait for the db service to be ready

  db:
    image: mysql:latest  # Use the official MySQL image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}  
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data

volumes:
  db_data:  # Define a volume for persistent MySQL data
